### ISSUE TITLE
Text operation keyboard shortcuts

### ISSUE THREAD

**Issue by CXuesong** [waf/PrettyPrompt#10]
I came here via https://github.com/waf/CSharpRepl .

I'm curious is there (or could there be) any support on the text selection and cut-copy-paste operations with keyboard shortcuts, like in PowerShell?

| Key | Function |
|----|----|
| Shift + ←→↑↓ | select text |
| Ctrl + A | select all |
| Ctrl + X | cut |
| Ctrl + C | copy |
| Ctrl + V | paste |
| Esc | clear input |

And it would be great if undo/redo is supported.

**Comment by waf** [comment]
Thanks for raising this! Currently, there isn't any support for text selection, but that's just because I haven't had time to design and implement it.

The main unknown for me is how text selection should work when text is selected with the mouse, and if we can detect it in a cross-platform way. Seeing what PowerShell Core and PSReadline do would be a good start.

There are some currently supported clipboard manipulation commands; Ctrl+Shift+C will copy the current line to the clipboard, and Ctrl-V will paste. This covers some of the use cases, but full text selection would be much better.

**Comment by CXuesong** [comment]
> Apparently PowerShell Core / PSReadLine ignore mouse selection, which makes sense.

Yeah. For console applications, I suppose mouse support is not a necessity, but a plus.

**Comment by waf** [comment]
Initial support for this is being worked on in the [`text-selection`](https://github.com/waf/PrettyPrompt/tree/text-selection) branch.

**Comment by waf** [comment]
This is now in the PrettyPrompt library (text selection, copy/paste, undo/redo). I'll make a release over the next few days, and incorporate it into csharprepl. Thanks for raising the issue!

**Comment by waf** [comment]
Done! You can update via `dotnet tool update -g csharprepl`
